# This file will be included by the Makefile under the project directory.

FLOAT_OBJ := $(FLOAT:.a=.o)
FLOAT_DEPS := lib-common/FLOAT.c
FLOAT_CFLAGS_EXTRA := -m32 -fno-builtin -Ilib-common


$(FLOAT): $(FLOAT_DEPS)
	mkdir -p obj/lib-common
	$(CC) -c lib-common/FLOAT.c -o $(FLOAT_OBJ) $(FLOAT_CFLAGS_EXTRA)
	ar cr obj/lib-common/FLOAT.a $(FLOAT_OBJ)

# TODO: write a rule for generating $(FLOAT_OBJ)
